import unittest
import tempfile
import os
import io
from pathlib import Path

from config import Config
from app import create_app
from src.domain.models.client import Client
from src.domain.models.purchase import Purchase
from src.domain.exceptions import DuplicateEntityException


class TestConfig(Config):
    TESTING = True
    DATABASE_PATH = ":memory:"
    DEFAULT_CONSULTA_HTML_PATH = "/Volumes/COS_202606/Consulta.html"
    SECRET_KEY = "test-secret"


class TestHexagonalApp(unittest.TestCase):
    def setUp(self):
        self.db_fd, self.db_path = tempfile.mkstemp()
        class RuntimeTestConfig(TestConfig):
            DATABASE_PATH = self.db_path

        self.app = create_app(RuntimeTestConfig)
        self.client = self.app.test_client()

    def tearDown(self):
        os.close(self.db_fd)
        if os.path.exists(self.db_path):
            os.unlink(self.db_path)

    def test_01_domain_models(self):
        c = Client(nombre="Juan Perez", cedula="123456", proceso_desempeno="Ambulancia", valor_a_descontar=150000)
        self.assertEqual(c.format_valor(), "$150,000.00")

        p = Purchase(client_id=1, concepto="Almuerzo", monto=25000, fecha_compra="2026-07-13")
        self.assertEqual(p.format_monto(), "$25,000.00")

    def test_02_auth_service(self):
        with self.app.app_context():
            # admin is seeded
            user = self.app.auth_service.authenticate("admin", "admin123")
            self.assertIsNotNone(user)
            self.assertEqual(user.username, "admin")

    def test_03_client_and_purchase_service(self):
        with self.app.app_context():
            # Check seeded clients from Consulta.html
            clients = self.app.client_service.list_clients()
            self.assertGreaterEqual(len(clients), 1)

            first_client = clients[0]
            purchase = self.app.purchase_service.register_purchase(
                client_id=first_client.id,
                concepto="Uniforme",
                monto=85000.0,
                fecha_compra="2026-07-13",
                notas="Factura 001"
            )
            self.assertEqual(purchase.monto, 85000.0)

            summary = self.app.purchase_service.get_client_financial_summary(first_client.id)
            self.assertEqual(summary["total_compras"], 85000.0)
            self.assertEqual(summary["saldo_neto"], first_client.valor_a_descontar + 85000.0)

    def test_04_web_endpoints(self):
        # GET login
        res = self.client.get("/auth/login")
        self.assertEqual(res.status_code, 200)

        # Login as admin
        res = self.client.post("/auth/login", data={"username": "admin", "password": "admin123"}, follow_redirects=True)
        self.assertEqual(res.status_code, 200)
        self.assertIn(b"Panel Ejecutivo HexOPS", res.data)

    def test_05_report_and_excel_generation(self):
        with self.app.app_context():
            service = self.app.report_service
            filename = service.format_report_filename("2026-05-20", "2026-06-19")
            self.assertEqual(filename, "Mayo 20 hasta Junio 19 2026.xlsx")

            excel_bytes, generated_fn = service.generate_report_excel("2026-05-20", "2026-06-19")
            self.assertGreater(len(excel_bytes), 100)
            self.assertEqual(generated_fn, "Mayo 20 hasta Junio 19 2026.xlsx")

            # Check openpyxl loading of generated bytes
            import openpyxl
            wb = openpyxl.load_workbook(io.BytesIO(excel_bytes))
            self.assertIn("Hoja 1", wb.sheetnames)
            ws = wb["Hoja 1"]
            self.assertEqual(ws.cell(2, 1).value, "Nombre")
            self.assertEqual(ws.cell(2, 4).value, "Valor a Descontar")

    def test_06_client_autocomplete_search_api(self):
        # Ensure logged in
        self.client.post("/auth/login", data={"username": "admin", "password": "admin123"}, follow_redirects=True)

        res = self.client.get("/clients/api/search?q=andres")
        self.assertEqual(res.status_code, 200)
        data = res.get_json()
        self.assertIsInstance(data, list)
        self.assertGreaterEqual(len(data), 1)

        names = [c["nombre"].lower() for c in data]
        self.assertTrue(any("andres" in n for n in names))

    def test_07_duplicate_purchase_detection(self):
        with self.app.app_context():
            clients = self.app.client_service.list_clients()
            client = clients[0]
            # Register a purchase
            self.app.purchase_service.register_purchase(
                client_id=client.id,
                concepto="Alimentación",
                monto=15000.0,
                fecha_compra="2026-07-13"
            )

            # Check service directly
            is_dup = self.app.purchase_service.check_duplicate_purchase(client.id, "2026-07-13", 15000.0)
            self.assertTrue(is_dup)

            is_not_dup = self.app.purchase_service.check_duplicate_purchase(client.id, "2026-07-13", 25000.0)
            self.assertFalse(is_not_dup)

        # Check via API endpoint
        self.client.post("/auth/login", data={"username": "admin", "password": "admin123"}, follow_redirects=True)
        res = self.client.get(f"/purchases/api/check_duplicate?client_id={client.id}&fecha_compra=2026-07-13&monto=15000")
        self.assertEqual(res.status_code, 200)
        self.assertTrue(res.get_json()["is_duplicate"])

    def test_08_single_client_purchase_history_filter(self):
        self.client.post("/auth/login", data={"username": "admin", "password": "admin123"}, follow_redirects=True)
        with self.app.app_context():
            client = self.app.client_service.list_clients()[0]
            self.app.purchase_service.register_purchase(
                client_id=client.id,
                concepto="Alimentación",
                monto=18500.0,
                fecha_compra="2026-07-13"
            )
            client_id = client.id
            client_nombre = client.nombre

        res = self.client.get(f"/purchases/?client_id={client_id}")
        self.assertEqual(res.status_code, 200)
        html = res.data.decode("utf-8")
        self.assertIn("CRONOLOGÍA DE FECHAS Y VALORES REGISTRADOS", html)
        self.assertIn("18,500.00", html)


if __name__ == "__main__":
    unittest.main()
