import unittest
import tempfile
import os
import io
from pathlib import Path

from config import Config
from app import create_app
from src.domain.models.client import Client
from src.domain.models.purchase import Purchase
from src.domain.exceptions import DuplicateEntityException


class TestConfig(Config):
    TESTING = True
    DATABASE_PATH = ":memory:"
    DEFAULT_CONSULTA_HTML_PATH = "/Volumes/COS_202606/Consulta.html"
    SECRET_KEY = "test-secret"


class TestHexagonalApp(unittest.TestCase):
    def setUp(self):
        self.db_fd, self.db_path = tempfile.mkstemp()
        class RuntimeTestConfig(TestConfig):
            DATABASE_PATH = self.db_path

        self.app = create_app(RuntimeTestConfig)
        with self.app.app_context():
            self.app.client_service.register_client("Andres Test", "12345678", "Pool de Ambulancia", 100000.0)
        self.client = self.app.test_client()

    def tearDown(self):
        os.close(self.db_fd)
        if os.path.exists(self.db_path):
            os.unlink(self.db_path)

    def test_01_domain_models(self):
        c = Client(nombre="Juan Perez", cedula="123456", proceso_desempeno="Ambulancia", valor_a_descontar=150000)
        self.assertEqual(c.format_valor(), "$150,000.00")

        p = Purchase(client_id=1, concepto="Almuerzo", monto=25000, fecha_compra="2026-07-13")
        self.assertEqual(p.format_monto(), "$25,000.00")

    def test_02_auth_service(self):
        with self.app.app_context():
            # admin is seeded
            user = self.app.auth_service.authenticate("admin", "admin123")
            self.assertIsNotNone(user)
            self.assertEqual(user.username, "admin")

    def test_03_client_and_purchase_service(self):
        with self.app.app_context():
            # Check seeded clients from Consulta.html
            clients = self.app.client_service.list_clients()
            self.assertGreaterEqual(len(clients), 1)

            first_client = clients[0]
            purchase = self.app.purchase_service.register_purchase(
                client_id=first_client.id,
                concepto="Uniforme",
                monto=85000.0,
                fecha_compra="2026-07-13",
                notas="Factura 001"
            )
            self.assertEqual(purchase.monto, 85000.0)

            summary = self.app.purchase_service.get_client_financial_summary(first_client.id)
            self.assertEqual(summary["total_compras"], 85000.0)
            self.assertEqual(summary["saldo_neto"], first_client.valor_a_descontar + 85000.0)

    def test_04_web_endpoints(self):
        # GET login
        res = self.client.get("/auth/login")
        self.assertEqual(res.status_code, 200)

        # Login as admin
        res = self.client.post("/auth/login", data={"username": "admin", "password": "admin123"}, follow_redirects=True)
        self.assertEqual(res.status_code, 200)
        self.assertIn(b"Panel Ejecutivo HexOPS", res.data)

    def test_05_report_and_excel_generation(self):
        with self.app.app_context():
            service = self.app.report_service
            filename = service.format_report_filename("2026-05-20", "2026-06-19")
            self.assertEqual(filename, "Mayo 20 hasta Junio 19 2026.xlsx")

            excel_bytes, generated_fn = service.generate_report_excel("2026-05-20", "2026-06-19")
            self.assertGreater(len(excel_bytes), 100)
            self.assertEqual(generated_fn, "Mayo 20 hasta Junio 19 2026.xlsx")

            # Check openpyxl loading of generated bytes
            import openpyxl
            wb = openpyxl.load_workbook(io.BytesIO(excel_bytes))
            self.assertIn("Hoja 1", wb.sheetnames)
            ws = wb["Hoja 1"]
            self.assertEqual(ws.cell(2, 1).value, "Nombre")
            self.assertEqual(ws.cell(2, 4).value, "Valor a Descontar")

    def test_06_client_autocomplete_search_api(self):
        # Ensure logged in
        self.client.post("/auth/login", data={"username": "admin", "password": "admin123"}, follow_redirects=True)

        res = self.client.get("/clients/api/search?q=andres")
        self.assertEqual(res.status_code, 200)
        data = res.get_json()
        self.assertIsInstance(data, list)
        self.assertGreaterEqual(len(data), 1)

        names = [c["nombre"].lower() for c in data]
        self.assertTrue(any("andres" in n for n in names))

    def test_07_duplicate_purchase_detection(self):
        with self.app.app_context():
            clients = self.app.client_service.list_clients()
            client = clients[0]
            # Register a purchase
            self.app.purchase_service.register_purchase(
                client_id=client.id,
                concepto="Alimentación",
                monto=15000.0,
                fecha_compra="2026-07-13"
            )

            # Check service directly
            is_dup = self.app.purchase_service.check_duplicate_purchase(client.id, "2026-07-13", 15000.0)
            self.assertTrue(is_dup)

            is_not_dup = self.app.purchase_service.check_duplicate_purchase(client.id, "2026-07-13", 25000.0)
            self.assertFalse(is_not_dup)

        # Check via API endpoint
        self.client.post("/auth/login", data={"username": "admin", "password": "admin123"}, follow_redirects=True)
        res = self.client.get(f"/purchases/api/check_duplicate?client_id={client.id}&fecha_compra=2026-07-13&monto=15000")
        self.assertEqual(res.status_code, 200)
        self.assertTrue(res.get_json()["is_duplicate"])

    def test_08_single_client_purchase_history_filter(self):
        self.client.post("/auth/login", data={"username": "admin", "password": "admin123"}, follow_redirects=True)
        with self.app.app_context():
            client = self.app.client_service.list_clients()[0]
            self.app.purchase_service.register_purchase(
                client_id=client.id,
                concepto="Alimentación",
                monto=18500.0,
                fecha_compra="2026-07-13"
            )
            client_id = client.id
            client_nombre = client.nombre

        res = self.client.get(f"/purchases/?client_id={client_id}")
        self.assertEqual(res.status_code, 200)
        html = res.data.decode("utf-8")
        self.assertIn("CRONOLOGÍA Y BASE DE DESCUENTO DEL CLIENTE", html)
        self.assertIn("18,500", html)


    def test_09_date_range_filtering(self):
        self.client.post("/auth/login", data={"username": "admin", "password": "admin123"}, follow_redirects=True)
        with self.app.app_context():
            client = self.app.client_service.list_clients()[0]
            self.app.purchase_service.register_purchase(
                client_id=client.id,
                concepto="Desayuno Mayo",
                monto=12000.0,
                fecha_compra="2026-05-25"
            )
            self.app.purchase_service.register_purchase(
                client_id=client.id,
                concepto="Almuerzo Junio",
                monto=15000.0,
                fecha_compra="2026-06-15"
            )
            client_id = client.id

        res = self.client.get(f"/clients/{client_id}?fecha_inicio=2026-06-01&fecha_fin=2026-06-30")
        self.assertEqual(res.status_code, 200)
        html = res.data.decode("utf-8")
        self.assertIn("Almuerzo Junio", html)
        self.assertNotIn("Desayuno Mayo", html)

        res2 = self.client.get(f"/purchases/?fecha_inicio=2026-05-01&fecha_fin=2026-05-31")
        self.assertEqual(res2.status_code, 200)
        html2 = res2.data.decode("utf-8")
        self.assertIn("Desayuno Mayo", html2)
        self.assertNotIn("Almuerzo Junio", html2)


    def test_10_import_clients_from_json(self):
        import json, tempfile, os
        test_clients = [
            {"nombre": "Cliente JSON Test", "cedula": "999888777", "proceso_desempeno": "Pool de Ambulancia"}
        ]
        fd, path = tempfile.mkstemp(suffix=".json")
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(test_clients, f)

        with self.app.app_context():
            imported, skipped = self.app.client_service.import_from_json_file(path)
            self.assertEqual(imported, 1)
            client = self.app.client_service.get_client_by_cedula("999888777")
            self.assertIsNotNone(client)
            self.assertEqual(client.nombre, "Cliente JSON Test")
            self.assertEqual(client.valor_a_descontar, 0.0)

        os.remove(path)

    def test_11_import_clients_via_file_upload(self):
        import io
        self.client.post("/auth/login", data={"username": "admin", "password": "admin123"}, follow_redirects=True)
        json_content = b'[{"nombre": "Cliente Subido Web", "cedula": "777666555", "proceso_desempeno": "Sistemas"}]'
        data = {
            "json_file": (io.BytesIO(json_content), "Consulta.json")
        }
        res = self.client.post("/clients/import_consulta", data=data, content_type="multipart/form-data", follow_redirects=True)
        self.assertEqual(res.status_code, 200)
        with self.app.app_context():
            client = self.app.client_service.get_client_by_cedula("777666555")
            self.assertEqual(client.nombre, "Cliente Subido Web")

    def test_12_ocr_service_matching_and_confirm(self):
        class DummyOcrPort:
            def analyze_handwritten_image(self, image_bytes, mime_type="image/jpeg"):
                return [
                    {"cliente_texto": "12345678", "concepto": "Almuerzo IA", "monto": 25000.0, "fecha": "2026-07-13"}
                ]

        with self.app.app_context():
            from src.application.services.ocr_service import OcrService
            ocr_srv = OcrService(DummyOcrPort(), self.app.client_service.client_repo)
            results = ocr_srv.analyze_sales_image(b"dummy")
            self.assertEqual(len(results), 1)
            self.assertEqual(results[0]["client_cedula"], "12345678")

        # Test POST confirmation via web
        self.client.post("/auth/login", data={"username": "admin", "password": "admin123"}, follow_redirects=True)
        with self.app.app_context():
            client = self.app.client_service.get_client_by_cedula("12345678")
            data = {
                "client_id": [str(client.id)],
                "concepto": ["Almuerzo Confirmado"],
                "monto": ["25000.0"],
                "fecha_compra": ["2026-07-13"]
            }
            res = self.client.post("/purchases/ocr/confirm", data=data, follow_redirects=True)
            self.assertEqual(res.status_code, 200)
            purchases = self.app.purchase_service.get_purchases_by_client(client.id)
            self.assertTrue(any(p.concepto == "Almuerzo Confirmado" for p in purchases))


if __name__ == "__main__":
    unittest.main()
